version: "3.0"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"
    environment:
      ALLOW_EMPTY_PASSWORD: "YES"
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8082:8081'
    depends_on:
      - redis
  adminer:
    image: adminer
    restart: always
    ports:
     - 8081:8080
volumes:
  db:
    driver: local
  redis-data:
    external: false
    driver: local